[package]
name = "mafuyu"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono ={ version = "0.4.39", features = ["serde"] }
colog = "1.3.0"
log = "0.4.25"
poise = "0.6.1"
reqwest = "0.12.12"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
