name: Build images/artifacts

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_call:
    inputs:
      upload-artifacts:
        description: Whether to upload artifacts.
        required: false
        default: true
        type: boolean
    outputs:
      key: 
        description: The Docker image tag.
        value: ${{ jobs.build-docker-image.outputs.tag }}

env:
  NODE_VERSION: 22
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ fromJson(steps.meta.outputs.json).tags[0] }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}
      
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        if: inputs.upload-artifacts
        with:
          name: docker-image
          path: /tmp/image.tar
          retention-days: 7

  build-aws-cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install NPM packages
        shell: bash
        run: npm ci
      
      - name: Synth AWS-CDK stack
        run: npx cdk synth --ci --no-lookups --strict

      - name: Upload synth artifact
        uses: actions/upload-artifact@v4
        if: inputs.upload-artifacts
        with:
          name: aws-cdk-synth
          path: cdk.out
