name: Build and deploy

on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch: 

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
    with:
      build-image-tag: ${{ needs.build.outputs.key }}